#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libzimg
Version  : 1
Release  : 4
URL      : https://github.com/sekrit-twc/zimg/archive/master.zip
Source0  : https://github.com/sekrit-twc/zimg/archive/master.zip
Summary  : Scaling, colorspace conversion, and dithering library
Group    : Development/Tools
License  : LGPL-3.0-or-later
Requires: libzimg-lib = %{version}-%{release}
BuildRequires : buildreq-configure

%description
z.lib
======
The "z" library implements the commonly required image processing basics of
scaling, colorspace conversion, and depth conversion. A simple API enables
conversion between any supported formats to operate with minimal knowledge
from the programmer. All library routines were designed from the ground-up
with correctness, flexibility, and thread-safety as first priorities.
Allocation, buffering, and I/O are cleanly separated from processing, allowing
the programmer to adapt "z" to many scenarios.

%package dev
Summary: dev components for the libzimg package.
Group: Development
Requires: libzimg-lib = %{version}-%{release}
Provides: libzimg-devel = %{version}-%{release}
Requires: libzimg = %{version}-%{release}

%description dev
dev components for the libzimg package.


%package doc
Summary: doc components for the libzimg package.
Group: Documentation

%description doc
doc components for the libzimg package.


%package lib
Summary: lib components for the libzimg package.
Group: Libraries

%description lib
lib components for the libzimg package.


%package staticdev
Summary: staticdev components for the libzimg package.
Group: Default
Requires: libzimg-dev = %{version}-%{release}

%description staticdev
staticdev components for the libzimg package.


%prep
%setup -q -n zimg-master
cd %{_builddir}/zimg-master

%build
## build_prepend content
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#
find . -type f -name 'configure' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIE/ /g' {} \;
autoreconf -v --install --force
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#
find . -type f -name 'configure' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIE/ /g' {} \;
find . -type f -name '*.m4' -exec sed -i 's/\-fPIE/ /g' {} \;
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587653416
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-O3 -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe"
export FCFLAGS="-O3 -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe"
export FFLAGS="-O3 -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe"
export CFFLAGS="-O3 -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe"
export LDFLAGS="-O3 -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-semantic-interposition -fno-stack-protector -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native"
export CXXFLAGS="-O3 -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=6 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -fvisibility-inlines-hidden -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe"
unset LD_AS_NEEDED
## altflags1 end
%configure  --enable-testapp --enable-example --enable-simd
## make_prepend content
find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#
find . -type f -name 'Makefile' -exec sed -i 's/\-fPIE/ /g' {} \;


## make_prepend end
make  %{?_smp_mflags}  V=1 VERBOSE=1

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587653416
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/zimg++.hpp
/usr/include/zimg.h
/usr/lib64/pkgconfig/zimg.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/zimg/COPYING
/usr/share/doc/zimg/ChangeLog
/usr/share/doc/zimg/README.md
/usr/share/doc/zimg/example/Makefile
/usr/share/doc/zimg/example/api_example.cpp
/usr/share/doc/zimg/example/api_example_c.c
/usr/share/doc/zimg/example/hdr_example.cpp
/usr/share/doc/zimg/example/interlace_example.cpp
/usr/share/doc/zimg/example/misc/aligned_malloc.h
/usr/share/doc/zimg/example/misc/argparse.cpp
/usr/share/doc/zimg/example/misc/argparse.h
/usr/share/doc/zimg/example/misc/mmap.cpp
/usr/share/doc/zimg/example/misc/mmap.h
/usr/share/doc/zimg/example/misc/win32_bitmap.cpp
/usr/share/doc/zimg/example/misc/win32_bitmap.h
/usr/share/doc/zimg/example/tile_example.cpp

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzimg.so
/usr/lib64/libzimg.so.2
/usr/lib64/libzimg.so.2.0.0

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libzimg.a
